"""Emit a unified diff between original kernel source and the generated one,
optionally opening a PR via the `gh` CLI when requested.

Security:
- target_file is resolved against repo_root and MUST be inside repo_root.
- Branch names embed a timestamp so concurrent runs don't collide.
- subprocess.run uses argv lists (no shell), check=True surfaces errors,
  exceptions abort before any further git operations.
"""

from __future__ import annotations

import difflib
import os
import subprocess
import time
from pathlib import Path


def _is_inside(parent: Path, child: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def emit_diff(
    repo_root: str,
    target_file: str,
    new_source: str,
    *,
    open_pr: bool = False,
    pr_title: str = "Convert kernel to NKI",
    pr_body: str = "Generated by kernel-forge-aws-transform.",
) -> dict:
    repo = Path(repo_root).resolve()
    if not repo.exists() or not repo.is_dir():
        return {"ok": False, "error": f"repo_root does not exist or is not a dir: {repo}"}

    target = Path(target_file)
    if not target.is_absolute():
        target = (repo / target).resolve()
    else:
        target = target.resolve()

    # SECURITY: refuse path traversal. target must be inside repo_root.
    if not _is_inside(repo, target):
        return {"ok": False, "error": "target_file escapes repo_root"}
    if not target.exists():
        return {"ok": False, "error": f"target file not found: {target}"}

    original = target.read_text(encoding="utf-8")
    diff = "".join(
        difflib.unified_diff(
            original.splitlines(keepends=True),
            new_source.splitlines(keepends=True),
            fromfile=str(target.relative_to(repo)),
            tofile=str(target.relative_to(repo)),
            n=3,
        )
    )

    target.write_text(new_source, encoding="utf-8")

    pr_url: str | None = None
    if open_pr:
        # Use a unique branch name per run to avoid collisions.
        branch = f"kernel-forge/nki-conversion-{int(time.time())}-{os.getpid()}"
        try:
            subprocess.run(
                ["git", "-C", str(repo), "checkout", "-b", branch],
                check=True, capture_output=True, text=True,
            )
            subprocess.run(
                ["git", "-C", str(repo), "add", "--", str(target)],
                check=True, capture_output=True, text=True,
            )
            subprocess.run(
                ["git", "-C", str(repo), "commit", "-m", pr_title],
                check=True, capture_output=True, text=True,
            )
            subprocess.run(
                ["git", "-C", str(repo), "push", "-u", "origin", branch],
                check=True, capture_output=True, text=True,
            )
            r = subprocess.run(
                ["gh", "pr", "create", "--title", pr_title, "--body", pr_body],
                cwd=str(repo), capture_output=True, text=True, check=True,
            )
            pr_url = r.stdout.strip()
        except subprocess.CalledProcessError as e:
            return {
                "ok": False,
                "diff": diff,
                "applied_to": str(target),
                "branch": branch,
                "error": f"{e.cmd}: {e.stderr or e.stdout or e}",
            }
        except FileNotFoundError as e:
            return {
                "ok": False,
                "diff": diff,
                "applied_to": str(target),
                "error": f"required CLI not found: {e}",
            }

    return {"ok": True, "diff": diff, "pr_url": pr_url, "applied_to": str(target)}
